services:
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data: